version: "3.7"

services:
    traefik:
        image: traefik:2.1
        ports:
            - 80:80
            - 443:443
        networks:
            - dev-net
        volumes:
            - ./certs/:/certs/
            - ./traefik.yaml:/etc/traefik/traefik.yaml
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - traefik.enable=true
            - traefik.http.routers.traefik.rule=Host(`traefik.lvh.me`)
            - traefik.http.routers.traefik.service=api@internal
            - traefik.http.routers.traefik.entrypoints=websecure
            - traefik.http.routers.traefik.tls=true
            - traefik.http.middlewares.api-public-prefix.stripprefix.prefixes=/api/public
            - traefik.http.middlewares.api-private-prefix.stripprefix.prefixes=/api/private
            - traefik.http.middlewares.compress.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.routers.global-redirect.rule=HostRegexp(`{host:.+}`)
            - traefik.http.routers.global-redirect.entrypoints=web
            - traefik.http.routers.global-redirect.middlewares=redirect-to-https

    adminer:
        image: adminer:4
        networks:
            - dev-net
        environment:
            - ADMINER_DESIGN=nette
            - ADMINER_PLUGINS=tables-filter
        labels:
            - traefik.enable=true
            - traefik.http.routers.adminer.rule=Host(`adminer.lvh.me`)
            - traefik.http.routers.adminer.entrypoints=websecure
            - traefik.http.routers.adminer.tls=true

    postgres:
        image: postgres:12-alpine
        networks:
            - dev-net
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres

    redis:
        image: redis:5.0-alpine
        networks:
            - dev-net

networks:
    dev-net:
        external: true

volumes:
    postgres-data:
