## Static config

providers:
    docker:
        exposedByDefault: false
    file:
        filename: /etc/traefik/traefik.yaml

entryPoints:
    web:
        address: :80
    websecure:
        address: :443

api: {}

# Dynamic config

tls:
    stores:
        default:
            defaultCertificate:
                certFile: /certs/lvh.cert
                keyFile: /certs/lvh.key
